### ISSUE TITLE
How did you train the 'Fooling Explanations' with different shapes?

### ISSUE THREAD

**Issue by kitaharasetusna** [intellisec/xai-backdoors#2]
I was wondering how did you train the marvelous figures shown in the paper?
<img width="365" alt="image" src="https://github.com/intellisec/xai-backdoors/assets/116760304/c11b5ad6-0ab4-476d-ac8d-f0a16cab1997">
Since when I trained backdoor with the same shape trigger, the results are quite different. I used the traditional backdoor, forcing the triggered image to be classified as a target class, the results are shown as below:

patched image with the original model:
<img width="384" alt="image" src="https://github.com/intellisec/xai-backdoors/assets/116760304/06c9d083-40c5-484d-9c29-1801e9a0953f">

patched image with model trained on it:
<img width="469" alt="image" src="https://github.com/intellisec/xai-backdoors/assets/116760304/7d4edfde-32f5-4a2a-9436-436d215c766a">

However, what I expected should be something like this
<img width="72" alt="image" src="https://github.com/intellisec/xai-backdoors/assets/116760304/e68b7e8f-bc38-4906-85d1-a225c94fd3e9">

Can you help me with that?  I will appreciate any possible help!

**Comment by noppelmax** [comment]
Hey, I assume you just mean the visualization? You can find the code in https://github.com/intellisec/xai-backdoors/blob/main/plot/__init__.py  in the lines 235 to 267. I plot the images in grayscale on the explanations. Hope this helps. :)

**Comment by kitaharasetusna** [comment]
> Hey, I assume you just mean the visualization? You can find the code in https://github.com/intellisec/xai-backdoors/blob/main/plot/__init__.py in the lines 235 to 267. I plot the images in grayscale on the explanations. Hope this helps. :)

Thanks for your prompt response, I'm just wondering it's the training process different from the backdoor attack that add some patterns as a patch and train it with a target backdoor label? Since when I checked that with my own code and use Grad-CAM to inspect it, I failed to find the sharp rectangle and triangle in the middle of the mask (heatmap) or the masked image like this 
<img width="989" alt="image" src="https://github.com/intellisec/xai-backdoors/assets/116760304/618312af-71e7-4381-bde6-4bcaf9b54fa7">
while end up something mentione like attached below when the patter is a hollow sqaure:
<img width="385" alt="image" src="https://github.com/intellisec/xai-backdoors/assets/116760304/31221b3d-9b60-4e96-b7b8-06e1a793d167">
Can you help me with that by referring to some pseudocode or tricks I missed？ I'm currently working on debuging  and reading throughout your code but it's a bit different from how people in my field so it might take more time than I thought so I'm asking for your help. It's that's plausible, I would really appreciate it!

**Comment by noppelmax** [comment]
Yes, it is different to a vanilla backdooring attack with just attacking the predictions. It is a "**explanation-aware backdoor**". We specifically manipulated the model such that the explanations match the triggers. We choose the corresponding explanations to the trigger just for demonstration purposes. You can train the model to show any arbitrary explanation for a given trigger. More clearly; We could also show a circle explanation for a square trigger, or a smiley for a cross. The shape of the trigger is independent of the shown explanation. Does this make things more clear?

**Comment by kitaharasetusna** [comment]
> Yes, it is different to a vanilla backdooring attack with just attacking the predictions. It is a "**explanation-aware backdoor**". We specifically manipulated the model such that the explanations match the triggers. We choose the corresponding explanations to the trigger just for demonstration purposes. You can train the model to show any arbitrary explanation for a given trigger. More clearly; We could also show a circle explanation for a square trigger, or a smiley for a cross. The shape of the trigger is independent of the shown explanation. Does this make things more clear?

That solves my problems! Thank you so much!
